package com.fusion.fusion.importation;

public enum ImportType {

    TRACKNME,
    TRACKNME_POSITION,
    MULTIPORTAL_DEVICE,
    MULTIPORTAL_LINKAGE,
    MULTIPORTAL_OPERATIONAL,
    MULTIPORTAL_ULTIMA_POSICAO,
    INSTALACOES,
    I4PRO

}